project_id = "pklrgeqnckzphzwrhlnr"

[functions.webhook-solicitacao]
verify_jwt = false

[functions.rate-limit]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.tracking]
verify_jwt = false